[package]
name = "kzg"
version = "0.1.0"
edition = "2021"

[dependencies]
blst = { git = 'https://github.com/subspace/blst.git', rev = "079887d2d05bb2d61df4ceef3d4c836228ebc6ff"}
sha2 = "0.10.6"

[features]
default = [
    "rand",
    "std",
]
rand = []
std = [
    "sha2/std"
]
minimal-spec = []
