name: CI Build

on: [push]

jobs:
  tmone:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy, rustfmt

# 1st team #########################################################

    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path Arkworks/Cargo.toml

    - uses: actions-rs/cargo@v1
      with:
        command: bench
        args: --manifest-path Arkworks/Cargo.toml

    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path Arkworks/Cargo.toml

  teamScratch:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy, rustfmt
# 3rd team #########################################################

    - name: "[blst-from-scratch] Tests"
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path blst-from-scratch/Cargo.toml

    - name: "[blst-from-scratch] Benchmark"
      uses: actions-rs/cargo@v1
      with:
        command: bench
        args: --manifest-path blst-from-scratch/Cargo.toml

#  - name: "[blst-from-scratch] Clippy"
#     uses: actions-rs/cargo@v1
#     with:
#     command: clippy
#     args: --manifest-path blst-from-scratch/Cargo.toml --all-targets --all-features -- -D warnings

# Incompatible with Windows CI
#    - name: "[blst-from-scratch] Formatting"
#      uses: actions-rs/cargo@v1
#      with:
#        command: fmt
#        args: --manifest-path blst-from-scratch/Cargo.toml

# Common ###########################################################

    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path kzg-bench/Cargo.toml
